#pragma once

namespace DHCP_Defines{
    enum opcode {
        Client_message = 1,
        Server_message
    };

    enum MessageType{
        Discover = 1,
        Offer,
        Request,
        Decline,
        Ack,
        NAK,
        Release,
        Inform,
        Force_Renew
    };

    enum OptionCode {
        Padding = 0,
        SubnetMask,
        TimeOffset,
        Router,
        ServerTime,
        ServerName,
        DnsServerAddress,
        ServerLog,
        ServerQuotes,
        LprServer,      // Printer Server Address
        ImpressServer,  // Impress Server Address
        RlpServer,
        Hostname,
        BootFileSize,
        MeritDumpFile,
        DnsClientName,
        SwapServer,
        RootPath,
        ExtensionFile,
        ForwardOnOff,
        SrcRteOnOff,
        PolicyFilter,
        MaxDgAssembly,
        DefaultIpTLL,
        MtuTimeout,
        MtuPlateu,
        MtuInterface,
        MtuSubnet,
        BroadcastAddress,
        MaskDiscovery,
        MaskSupplier,
        RouterDiscovery,
        RouterRequest,
        StaticRoute,
        Trailers,
        ArpTimeout,
        Ethernet,
        DefaultTcpTLL,
        KeepaliveTime,
        KeepaliveData,
        NisDomain,
        NisServer,
        NtpServer,
        VendorSpecific,
        NetbiosNameServer,
        NetbiosDistributionDatagram,
        NetbiosNodeType,
        NetbiosScope,
        XWindowFont,
        XWindowManager,
        AddressRequest,
        LeasingAddressTime,
        Overload,
        DhcpMessageType,
        DhcpServerIdentifier,
        ParameterList,
        DhcpMessage,
        DhcpMaxMessageSize,
        RenewalTime,
        RebindingTime,
        ClassIdentifier,
        ClienIdentifier,
        NetWareIpDomainName,
        NetWareIpOption,
        NisDomainName,
        NisServerAddress,
        FtpServerName,
        BootfileName,
        HomeAgentsAddress,
        SmtpServerAddress,
        Pop3ServerAddress,
        NntpServerAddress,
        WwwServerAddress,
        FingerServerAddress,
        IrcServerAddress,
        StreetTalkServerAddress,
        StdaServerAddress,
        UserClass,
        DirectoryAgent,
        ServiceScope,
        RapidCommit,
        ClientFqdn,
        RelayAgentInformation,
        InternetStorageNameService,
        Unassgined_0,                   // Not assigned Options
        NdsServer
    };
}